In [1]:
import numpy as np

In [10]:
np.arange(-10, 11)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [11]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
np.arange(1, 101, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [17]:
np.arange(0, 10, 0.1) 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [18]:
np.arange(50, 101).sum()

3825

In [25]:
np.random.randint(10, size=(5, 10)).mean(axis=1)

array([3.7, 3.2, 5.2, 5.4, 4.7])

In [26]:
np.random.randint(10, size=(5, 10)).sum(axis=0)

array([24, 21, 17, 19, 25, 21, 22, 22, 15, 23])

In [30]:
x = np.random.random(10)
x[x > 0.5]

array([0.62781187, 0.57952391, 0.58492155, 0.86840008])

In [31]:
np.arange(1, 21) ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [34]:
y = np.arange(1, 21) ** 2
y[y % 2 == 0]

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [50]:
z = np.random.randint(100, size=10)
m = z.max()
m

81

In [51]:
z[z > (m * 0.8)]

array([74, 72, 81])

In [58]:
a = np.random.randint(10, size=(10, 10))

In [62]:
a.mean(axis=1)

array([5.6, 3.9, 4.5, 3.1, 4.6, 5. , 5. , 5.4, 2.8, 5.1])

In [65]:
a[a.mean(axis=1) > 5]

array([[8, 1, 8, 8, 2, 9, 9, 4, 1, 6],
       [2, 9, 3, 4, 5, 0, 9, 9, 5, 8],
       [9, 6, 5, 0, 6, 4, 4, 8, 3, 6]])

In [66]:
b = np.random.randint(10, size=100)
c = np.random.randint(10, size=100)

In [67]:
b == c

array([False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
        True])

In [68]:
# Gleiche Werte
b[b == c]

array([4, 7, 1, 3, 1, 2, 0, 7, 4, 9, 9])

In [99]:
# Stellen
np.arange(100)[b == c]

array([ 4, 11, 20, 22, 56, 61, 65, 84, 92, 95, 99])

In [105]:
# Beides gleichzeitig
maske = b == c
np.vstack((np.arange(100)[maske], b[maske], c[maske]))

array([[ 4, 11, 20, 22, 56, 61, 65, 84, 92, 95, 99],
       [ 4,  7,  1,  3,  1,  2,  0,  7,  4,  9,  9],
       [ 4,  7,  1,  3,  1,  2,  0,  7,  4,  9,  9]])