# Numpy
= Number Python
Verabeitung von Zahlen
Kann alles Mathematische
- normale Funkitonen
- Berechnungen mit Listen(1D, 2D, 3D)


In [2]:
import numpy as np

## Array

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
a

array([1, 2, 3, 4, 5, 6])

## Index

In [5]:
a[0]

np.int64(1)

In [6]:
a[1]

np.int64(2)

In [7]:
a[-1] # lezter Eintrag im Array

np.int64(6)

In [8]:
a[-2]

np.int64(5)

In [9]:
a[0:2]

array([1, 2])

In [10]:
a[3:-1]

array([4, 5])

In [11]:
a[3:]

array([4, 5, 6])

## Eigenschaften

In [12]:
len(a) #Länge einer Dimension eines Arrays

6

In [13]:
a.size #Gesamtanzahl der Elemente

6

In [14]:
a.shape # Form z.B. (3,2) 3 Zeilen 2 Spalten oder umgekehrt

(6,)

In [15]:
a.ndim # Anz. Dimensionen

1

In [16]:
a.dtype #Datentyp der Elemente

dtype('int64')

## Datentypen
Ganzahlen
- int8
- int16
- int32
- int64

Kommazahlen
- float16
- float32
- float64

In [17]:
b = np.array([1,2,3,4], dtype=np.int8)

In [18]:
b

array([1, 2, 3, 4], dtype=int8)

## Matrix
= 2D-Array

In [19]:
c=np.array([[1,2,3], [4,5,6], [7,6,6]])
           # Funktionen/Egenschaften sind gleich wie bei 1D-Array

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 6]])

In [21]:
c.sum()

np.int64(40)

In [22]:
c.mean()

np.float64(4.444444444444445)

In [23]:
c[0].sum()

np.int64(6)

In [24]:
c[0][1]

np.int64(2)

In [25]:
c.sum(axis=0) # Summe der Spalten

array([12, 13, 15])

In [26]:
c.sum(axis=1) # Summe der Zeilen

array([ 6, 15, 19])

In [27]:
c.mean(axis=0) # Durchschnitt der Spalten

array([4.        , 4.33333333, 5.        ])

In [28]:
# Breich genieren lassen
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Vektorisierung
Gesamtes Array mit einer Operation ansprechen

Beliebige Operationen auf jedes Element des Arrays benutzen

In [30]:
d = np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
d+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [32]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
d/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [34]:
d*15

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180,
       195, 210, 225, 240, 255, 270, 285])

In [35]:
d*d

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

2 Arrays miteinander vektorisieren

In [36]:
e = np.arange(10,30)
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [37]:
d*e

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200, 231, 264,
       299, 336, 375, 416, 459, 504, 551])

In [38]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 6]])

In [39]:
c*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 12, 12]])

In [40]:
c*c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 36, 36]])

## Boolean Masken
Ergebnis eine Vektorisierung mit einem boolschen Operator

im Endeffekt ein Array mit True/False

Wird immer für Filterungen verwendet (später bei Pandas, Matplotlib und ML)


In [41]:
f = np.arange(10)

In [42]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
maske = f%2==0
maske

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [44]:
f[maske]

array([0, 2, 4, 6, 8])

In [45]:
f[f<5]

array([0, 1, 2, 3, 4])

## Performance

In [46]:
import time

In [47]:
def measureTime(func):
    start=time.time()
    func()
    end=time.time()
    print(end-start)

In [48]:
anz = 100_000_000

In [49]:
def pythonList():
    x=list(range(anz))
    del(x)

In [50]:
def numpyArray():
    x=np.arange(anz)
    del(x)

In [51]:
def numpyRange():
    x=np.array(range(anz))
    del(x)


In [55]:
measureTime(pythonList)
measureTime(numpyArray)
measureTime(numpyRange)

5.335590362548828
0.3052561283111572
12.18529462814331


## Weitere Funktionen


Random


In [62]:
np.random.random()

0.21628674856097696

In [63]:
np.random.random(size=(10))

array([0.47645444, 0.92777232, 0.521298  , 0.59386525, 0.06816298,
       0.25530309, 0.62138309, 0.60229351, 0.29548947, 0.25578875])

In [64]:
np.random.random(size=(5,5))

array([[0.72720386, 0.45930074, 0.90364254, 0.07833204, 0.45843444],
       [0.59762039, 0.86297857, 0.446792  , 0.99733091, 0.94152956],
       [0.13456915, 0.2286513 , 0.62733969, 0.91314989, 0.38053662],
       [0.935923  , 0.98910289, 0.71458979, 0.20013142, 0.60968201],
       [0.80141841, 0.5540717 , 0.30887424, 0.24512309, 0.64311287]])

In [70]:
np.random.randint(10)

7

In [72]:
np.random.randint(10, size= (10,5), dtype= np.int8)

array([[2, 9, 1, 6, 1],
       [5, 9, 4, 7, 4],
       [0, 4, 3, 6, 0],
       [5, 5, 4, 5, 0],
       [2, 6, 0, 4, 1],
       [7, 2, 7, 8, 8],
       [8, 7, 5, 2, 8],
       [4, 7, 1, 0, 2],
       [2, 4, 2, 9, 3],
       [9, 5, 4, 9, 0]], dtype=int8)

reshape: Form eines Arrays verändern (1D -> 2D, 2D -> 1D)

In [73]:
h = np.random.randint(10, size= (10,5), dtype= np.int8)
h

array([[3, 7, 2, 2, 2],
       [9, 1, 6, 5, 2],
       [7, 1, 5, 0, 9],
       [8, 2, 8, 5, 5],
       [0, 5, 9, 7, 3],
       [2, 7, 2, 1, 9],
       [3, 6, 8, 0, 9],
       [1, 5, 1, 0, 2],
       [5, 9, 0, 5, 4],
       [8, 7, 5, 1, 2]], dtype=int8)

In [74]:
h.reshape(50)

array([3, 7, 2, 2, 2, 9, 1, 6, 5, 2, 7, 1, 5, 0, 9, 8, 2, 8, 5, 5, 0, 5,
       9, 7, 3, 2, 7, 2, 1, 9, 3, 6, 8, 0, 9, 1, 5, 1, 0, 2, 5, 9, 0, 5,
       4, 8, 7, 5, 1, 2], dtype=int8)

In [75]:
h.reshape(h.size)

array([3, 7, 2, 2, 2, 9, 1, 6, 5, 2, 7, 1, 5, 0, 9, 8, 2, 8, 5, 5, 0, 5,
       9, 7, 3, 2, 7, 2, 1, 9, 3, 6, 8, 0, 9, 1, 5, 1, 0, 2, 5, 9, 0, 5,
       4, 8, 7, 5, 1, 2], dtype=int8)

In [76]:
h.reshape(-1)

array([3, 7, 2, 2, 2, 9, 1, 6, 5, 2, 7, 1, 5, 0, 9, 8, 2, 8, 5, 5, 0, 5,
       9, 7, 3, 2, 7, 2, 1, 9, 3, 6, 8, 0, 9, 1, 5, 1, 0, 2, 5, 9, 0, 5,
       4, 8, 7, 5, 1, 2], dtype=int8)

In [77]:
#h.reshape(48) reshape muss immer gleich viel Elemente haben wie der Ursprung

ValueError: cannot reshape array of size 50 into shape (48,)

In [78]:
h.reshape(2,25)

array([[3, 7, 2, 2, 2, 9, 1, 6, 5, 2, 7, 1, 5, 0, 9, 8, 2, 8, 5, 5, 0, 5,
        9, 7, 3],
       [2, 7, 2, 1, 9, 3, 6, 8, 0, 9, 1, 5, 1, 0, 2, 5, 9, 0, 5, 4, 8, 7,
        5, 1, 2]], dtype=int8)

In [79]:
h.reshape(5,10)


array([[3, 7, 2, 2, 2, 9, 1, 6, 5, 2],
       [7, 1, 5, 0, 9, 8, 2, 8, 5, 5],
       [0, 5, 9, 7, 3, 2, 7, 2, 1, 9],
       [3, 6, 8, 0, 9, 1, 5, 1, 0, 2],
       [5, 9, 0, 5, 4, 8, 7, 5, 1, 2]], dtype=int8)

linspace
Erzeugt ein Array von X bis Y mit n Elementen
Alle Abstände sind gleich groß

In [80]:
np.linspace(0,20,101)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

In [81]:
np.arange(0,101)/5

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

zeros, ones
Erzeugt Array mit nur 0 oder 1


In [82]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
np.ones(10)==1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

hstack, vstack
Arrays zusammenbauen (Horizontal oder Vertikal)

In [85]:
h

array([[3, 7, 2, 2, 2],
       [9, 1, 6, 5, 2],
       [7, 1, 5, 0, 9],
       [8, 2, 8, 5, 5],
       [0, 5, 9, 7, 3],
       [2, 7, 2, 1, 9],
       [3, 6, 8, 0, 9],
       [1, 5, 1, 0, 2],
       [5, 9, 0, 5, 4],
       [8, 7, 5, 1, 2]], dtype=int8)

In [86]:
r= h[5:]

In [87]:
r

array([[2, 7, 2, 1, 9],
       [3, 6, 8, 0, 9],
       [1, 5, 1, 0, 2],
       [5, 9, 0, 5, 4],
       [8, 7, 5, 1, 2]], dtype=int8)

In [88]:
l = h[:5]

In [89]:
l

array([[3, 7, 2, 2, 2],
       [9, 1, 6, 5, 2],
       [7, 1, 5, 0, 9],
       [8, 2, 8, 5, 5],
       [0, 5, 9, 7, 3]], dtype=int8)

In [90]:
np.hstack([l, r])

array([[3, 7, 2, 2, 2, 2, 7, 2, 1, 9],
       [9, 1, 6, 5, 2, 3, 6, 8, 0, 9],
       [7, 1, 5, 0, 9, 1, 5, 1, 0, 2],
       [8, 2, 8, 5, 5, 5, 9, 0, 5, 4],
       [0, 5, 9, 7, 3, 8, 7, 5, 1, 2]], dtype=int8)

In [91]:
np.vstack([l,r])

array([[3, 7, 2, 2, 2],
       [9, 1, 6, 5, 2],
       [7, 1, 5, 0, 9],
       [8, 2, 8, 5, 5],
       [0, 5, 9, 7, 3],
       [2, 7, 2, 1, 9],
       [3, 6, 8, 0, 9],
       [1, 5, 1, 0, 2],
       [5, 9, 0, 5, 4],
       [8, 7, 5, 1, 2]], dtype=int8)